from evaris_client.client import EvarisClient, EvarisError, EvarisStreamError, EvarisAPIError
from evaris_client.types import (
    TestCase,
    MetricScore,
    TestResultItem,
    AssessmentSummary,
    AssessmentResult,
    AssessmentProgressEvent,
    EvalConfig,
    EvalStatus,
    JudgeConfig,
    Observation,
    TraceResult,
    LogResult,
    LogLevel,
    TraceStatus,
    ObservationType,
    ExperimentConfig,
    ExperimentResult,
    ComplianceFramework,
    ComplianceStatus,
    ComplianceRule,
    ComplianceCheckResult,
    ProgressCallback,
    AsyncProgressCallback,
)

__version__ = "0.2.0"

__all__ = [
    "EvarisClient",
    "EvarisError",
    "EvarisStreamError",
    "EvarisAPIError",
    "TestCase",
    "MetricScore",
    "TestResultItem",
    "AssessmentSummary",
    "AssessmentResult",
    "AssessmentProgressEvent",
    "EvalConfig",
    "EvalStatus",
    "JudgeConfig",
    "Observation",
    "TraceResult",
    "LogResult",
    "LogLevel",
    "TraceStatus",
    "ObservationType",
    "ExperimentConfig",
    "ExperimentResult",
    "ComplianceFramework",
    "ComplianceStatus",
    "ComplianceRule",
    "ComplianceCheckResult",
    "ProgressCallback",
    "AsyncProgressCallback",
]
